// Supabase configuration
const SUPABASE_URL = 'https://tjjnkcwtuxpwictlkkit.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqam5rY3d0dXhwd2ljdGxra2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODEwNjIsImV4cCI6MjA2NTQ1NzA2Mn0.NvfJjt27Dj4lqFBD-UVdEDY4up0NM3K6yqA9JecsYdQ'; 